# Unique name for this workflow
name: Salesforce DX CI (packaging)

# Definition when the workflow should run
on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - prerelease/spring[2-9][0-9]
            - prerelease/summer[2-9][0-9]
            - prerelease/winter[2-9][0-9]
        paths:
            - 'force-app/**'

# Jobs to be executed
jobs:
    formatting-and-linting:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v1

            # Cache node_modules to speed up the process
            - name: Restore node_modules cache
              id: cache-npm
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-${{ env.cache-name }}-
                      npm-

            # Install npm dependencies for Prettier and Jest
            - name: 'Install npm dependencies'
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: npm install

            # Prettier formatting
            - name: 'Code formatting verification with Prettier'
              run: npm run prettier:verify

            # ESlint
            - name: 'Lint Lightning Web Components'
              run: npm run lint:lwc

            # Unit tests
            - name: 'Unit test Lightning Web Components'
              run: npm run test:unit:coverage

    packaging:
        runs-on: ubuntu-latest
        needs: formatting-and-linting
        steps:
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v1

            # Store secret for dev hub
            - name: 'Populate auth file with DEVHUB_PREREL_SFDX_URL secret'
              run: 'echo ${{ secrets.DEVHUB_PREREL_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'

            # Install and update Salesforce CLI
            - name: 'Install Salesforce CLI'
              run: 'sudo npm install -g sfdx-cli'

            # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: 'sfdx force:auth:sfdxurl:store --sfdxurlfile=./DEVHUB_SFDX_URL.txt --setalias=devhub --setdefaultdevhubusername'

            # Create package version
            - name: 'Create package version'
              id: package-version-create
              run: 'sfdx force:package:version:create -p LWCRecipes -x -w 20 --json'

            # Extract data from package version create result
            - name: 'Extract package:version:create result data'
              id: extract-data-package-version-create
              uses: muenzpraeger/github-action-extract-sfdx-packaging-result@master
              with:
                  json: ${{steps.package-version-create.outputs.result}}
