# Unique name for this workflow
name: Salesforce DX CI (packaging)

# Definition when the workflow should run
on:
    pull_request:
        types: [opened, synchronize, reopened]

# Jobs to be executed
jobs:
    env:
        PACKAGE_VERSION_RESULT: ""
        PACKAGE_VERSION_USERNAME: ""
    scratch-org-test:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v1

            # Install salesforcedx pre-release plugin
            - name: 'Install salesforcedx pre-release plugin'
              uses: forcedotcom/salesforcedx-actions@master
              if: startsWith(github.head_ref, 'prerelease')
              with:
                  args: 'plugins:install salesforcedx@pre-release'

            # Store secret for dev hub
            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
              shell: bash
              run: 'echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt'

            # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              uses: forcedotcom/salesforcedx-actions@master
              with:
                  args: 'force:auth:sfdxurl:store --sfdxurlfile=./DEVHUB_SFDX_URL.txt --setalias=devhub --setdefaultdevhubusername'

            # Lint Aura components
            - name: 'Show org data'
              uses: forcedotcom/salesforcedx-actions@master
              id: org-data
              with:
                  args: 'force:org:display -u devhub --json'

            # Test if package version creation was successful, otherwise fail the workflow
            - name: 'Test package version creation status'
              id: test2
              run: |
                  echo "aa"
                  echo ${{ steps.package-version.outputs.result }} | jq '.status'
                  echo "bb"
                  echo $JSON_RESULT_1 | jq '.status'
                  echo "cc"
                  echo $JSON_RESULT_1 | jq '.result.username'
                  export PACKAGE_VERSION_RESULT = $JSON_RESULT_1
                  export PACKAGE_VERSION_USERNAME = $JSON_RESULT_1 | jq '.result.username'
                  export BLUBBER = $JSON_RESULT_1 | jq '.result.username'
                  echo "::set-env name=BLIBBER::$BLUBBER"
                  echo "::set-env name=blebber::$BLUBBER"
              env:
                  JSON_RESULT_1: ${{ steps.org-data.outputs.result }}
            # Test if package version creation was successful, otherwise fail the workflow
            - name: 'Test2'
              run: |
                  echo $BLIBBER
                  echo $PACKAGE_VERSION_USERNAME
                  echo {{ steps.test2.env.blebber }}
