# Unique name for this workflow
name: SFDX CI

# Definition when the workflow should run
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

# Jobs to be executed
jobs:
  preparations:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code in the pull request
      - uses: actions/checkout@v1

      # Install an action that provides access to node.js
      - uses: actions/setup-node@v1

      # Install npm dependencies for Prettier and Jest
      - name: 'Install npm dependencies'
        run: npm install

  formatting-and-linting:
    runs-on: ubuntu-latest
    needs: preparations
    steps:        
      # Prettier formatting
      - name: 'Code formatting verification with Prettier'
        run: npm run prettier:verify

      # ESlint
      - name: 'Lint Lightning Web Components'
        run: npm run lint:lwc

      # Unit tests
      - name: 'Unit test Lightning Web Components'
        run: npm run test:unit:coverage

  dx-setup:
    runs-on: ubuntu-latest
    needs: formatting-and-linting
    steps:    
      # Store secret for dev hub
      - name: 'Populate auth file with SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.DEV_HUB_SFDXURL}} > ./SFDX_URL_STORE.txt'

      # Authenticate dev hub
      - name: 'Authenticate Dev Hub'
        uses: forcedotcom/salesforcedx-actions@master
        with:
           args: 'force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=devhub --setdefaultdevhubusername'

      # Lint Aura components (needs)
      - name: 'Lint Aura components'
        run: npm run lint:aura

  
      # Create scratch org
      - name: 'Create scratch org'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:org:create -f config/project-scratch-def.json -a scratch-org -s'     

      # Deploy source to scratch org
      - name: 'Push source to scratch org'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:source:push -u scratch-org'

      # Assign permission set
      - name: 'Assign permission set to default user'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:user:permset:assign -n recipes'

      # Import sample data
      - name: 'Import sample data'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:data:tree:import --plan ./data/data-plan.json'

      # Run Apex tests in scratch org
      - name: 'Run Apex tests'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:apex:test:run --codecoverage --resultformat=tap'

      # Housekeeping
      - name: 'Delete scratch org'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:org:delete -p -u scratch-org'